<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  Reads every Mod/Languages/French/{Keyed,DefInjected}/**/*.xml key (this mod has no Keyed
  folder — Fox_Lamp is a static Def, not code-generated text). For each key, resolves the
  English text: a matching Mod/Languages/English file+key if one exists, otherwise the native
  English value read directly from the shipped Def in Mod/Defs (label/description resolved by
  dotted path against the Def's own XML, mirroring how the game itself falls back). This is why
  the file is built by a script, not by hand: the fallback path differs key by key, and a
  hand-copy cannot be trusted not to drift. Adapted from FoodCourt/_tools/Generate-FrenchReview.ps1.

  Original (source-language) text: the piece was originally written by AmliFurx in Chinese; the
  Chinese source (`不！准！吃！竹！笋！！！！`) is quoted once in this mod's ATTRIBUTION.md but is
  not stored anywhere in the repository as separate, parseable data — only the ported English and
  French remain. So Original equals English throughout, same as English, noted once here rather
  than on every row.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

function Resolve-DefField($defsRoot, [string]$key) {
    # key looks like "DefName.field" or "DefName.stages.N.field" or "DefName.tools.N.label"
    $parts = $key -split '\.'
    $defName = $parts[0]
    $rest = $parts[1..($parts.Length - 1)]
    if (-not $script:defCache.ContainsKey($defName)) {
        $found = $null
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            $node = $x.SelectSingleNode("//*[defName='$defName']")
            if ($node) { $found = $node; break }
        }
        $script:defCache[$defName] = $found
    }
    $node = $script:defCache[$defName]
    if (-not $node) { return $null }
    $cur = $node
    foreach ($p in $rest) {
        if ($cur -eq $null) { return $null }
        if ($p -match '^\d+$') {
            $children = @($cur.ChildNodes | Where-Object { $_.NodeType -eq 'Element' })
            $idx = [int]$p
            if ($idx -ge $children.Count) { return $null }
            $cur = $children[$idx]
        } else {
            $cur = $cur.$p
        }
    }
    if ($cur -is [System.Xml.XmlElement]) { return $cur.InnerText }
    if ($cur) { return [string]$cur }
    return $null
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$englishRoot = Join-Path $Root 'Mod/Languages/English'
$defsRoot = Join-Path $Root 'Mod/Defs'
$script:defFiles = Get-ChildItem $defsRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName }
$script:defCache = @{}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by `_tools/Generate-FrenchReview.ps1` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** AmliFurx wrote the piece in Chinese; the")
[void]$out.AppendLine("Chinese source is quoted once in ATTRIBUTION.md but is not stored in this repository as")
[void]$out.AppendLine("separate, parseable data — only the ported English and French remain. English is the closest")
[void]$out.AppendLine("available original for every row.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: working tree at commit 01de97c.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    $enPath = Join-Path $englishRoot $rel
    $enEntries = Get-Entries $enPath

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $orig = Resolve-DefField $defsRoot $key
        $en = $null
        if ($enEntries.Contains($key)) { $en = $enEntries[$key] }
        elseif ($null -ne $orig) { $en = $orig }
        if ($null -eq $orig) { $orig = '*(not found — check by hand)*' }
        if ($null -eq $en) { $en = '*(not found — check by hand)*' }
        $flag = if ($fr -match '\?\?\?|TODO|\{PAWN_gender' -and $fr -notmatch '\{PAWN_gender \? ') { ' | ?' } else { '' }
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
